### ISSUE TITLE
Saved themes disappear after Browser close

### ISSUE THREAD

**Issue by katastrophe92** [mozilla/FirefoxColor#1047]
Hello FirefoxColor :)

Idk if I'm doing something wrong but my saved themes are gone after browser(LibreWolf) is closed. Also if I export my theme, how can I import it back?

.gif was too big to be posted here: https://streamable.com/qt3dt1
or this one: - https://i.postimg.cc/LsjkWFq1/librewolf-11-11-36-25-March2023.gif
                  - https://postimg.cc/f3T03Ffz

Thanks

**Comment by aamirazad** [comment]
I wasn't able to replicate this on (regular) Firefox. Could it be a container tabs related bug? Also the export is only to look at the code or upload the theme to the Firefox Add-ons Marketplace, not as a backup. Your custom colors should sync via your Mozilla account. Though it might be different or not work because LibreWolf.

**Comment by katastrophe92** [comment]
I use only LibreWolf without Firefox sync. I didn't try on Firefox. Only what I know is that on librewolf is not working.
