### ISSUE TITLE
The "Save" button is not re-enabled for a previously saved theme after it is deleted from the "Saved themes" area

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#312]
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (0.0.39 custom built on 30.05.2018) installed.
- Have at least a theme saved.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on any theme from the "Saved themes" area.
3. Hover over the same theme from step 2 and click the delete button.
4. Observe the "Save" button's status.

**[Expected result]:**
- The "Save" button is re-enabled.

**[Actual result]:**
- The "Save" button is still disabled.

**[Notes]:**
- This issue is reproducible after the "Firefox Color" tab is reopened.
- This issue is still reproducible after browser restart.
- This issue is also reproducible if you apply another theme and you go back to the previously deleted one using the "Undo" button.
- This issue is no longer reproducible if the "Firefox Color" tab is reopened, a change is made to the theme and the "Undo" button is pressed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40718585-3de56862-6419-11e8-9ffa-338201dc29b0.gif)

**Comment by rebmullin** [comment]
Since the ui has changed, I will close for now but please reopen if this is the expectation.

**Comment by heres-maria** [comment]
I have verified that this issue is not reproducible on the new UI version of the stage website. Deleting a theme will re-enable the Save button. Using the undo button to return to the deleted theme will also not disable the button. As such, I am marking this as verified fixed. 
Tested using Nightly 77.0a1 (Build ID: 20200504093644 ), Firefox Beta 76.0 (Build ID: 20200427162639), Firefox Release 75 (Build ID: 20200403170909) on Windows 10 x64, Mint 19.2, Mac 10.14.6.
