### ISSUE TITLE
Cannot make finish-visit fire

### ISSUE THREAD

**Issue by johngruen** [mozilla/FirefoxColor#322]
finish-visit does not appear to be firing as intended. I see no record of it on the GA event logs.

**Comment by johngruen** [comment]
@lmorchard maybe something to look at on monday if possible?

**Comment by lmorchard** [comment]
Oh, huh: Nothing in the add-on or the site actually makes a metrics ping for finish-visit. I think this just fell off my radar.

But also, now that I look at what [it's supposed to be called for](https://github.com/mozilla/FirefoxColor/blob/964141d8dbc6c70c57da9bcf9151ce6da1ca2bf0/docs/metrics.md#finish-visit)... What does "leave the site" mean? That is, when exactly should this get sent? Guessing off the top of my head:

* Whenever a Color tab is closed?
* Whenever a link is clicked on the page that is not Color?
* If the URL changes in an existing tab to a non-Color site?

I can probably catch an event on tab close. But, detecting the transition to a different site could be tricky, because our add-on only has permissions for the Color site itself. Will need to experiment a bit
