### ISSUE TITLE
Randomize button

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#350]
One of my favorite features of character creators in video games is a randomize button. Might be fun to have one in Color, even if it makes ridiculously ugly themes

**Comment by pdehaan** [comment]
But if we generated a single random color and then passed it to the palette generator concept in #330, we may be less likely to get ridiculously ugly themes (tm).

**Comment by weivicky** [comment]
![image](https://user-images.githubusercontent.com/10877399/41931411-fe55ef26-794b-11e8-9a2d-ac55f24f3e86.png)

![image](https://user-images.githubusercontent.com/10877399/41931715-da625a36-794c-11e8-8403-d501d9601a2a.png)
Button states: https://design.firefox.com/photon/components/buttons.html

Undo icon: https://firefoxux.github.io/icons/viewer/#undo
Redo icon: https://firefoxux.github.io/icons/viewer/#redo
Randomize icon: https://thenounproject.com/search/?q=randomize&i=1402452

**Comment by lmorchard** [comment]
So we have a button... do we have a notion of what it should do? Easiest first implementation is simply randomizing all the properties for ugly fun. But, there's been talk of making it more smart about complementary colors.

**Comment by johngruen** [comment]
@lmorchard Looks like tinycolor has some palette generator functions we could use. Lets' start by testing out a full random. I also made two seeded semi-random 4 value generator functions you could use to start making semi-random palettes. We could set this up so that each hit of the random buttom selects a fully randomized theme, a mono theme, or a tetrad theme. 

https://codepen.io/johngruen/pen/OEaxLE

**Comment by lmorchard** [comment]
https://github.com/mozilla/FirefoxColor/commit/2043971ba4354b1d4d35b870ca5ec4e372ac4b07
