### ISSUE TITLE
Allow users to preview shared themes.

### ISSUE THREAD

**Issue by sevaan** [mozilla/FirefoxColor#361]
When viewing a shared theme, hovering over the preview image should allow the user to preview it in their browser chrome before they apply it.

<img width="602" alt="screen shot 2018-06-19 at 3 07 51 pm" src="https://user-images.githubusercontent.com/473531/41667811-e1bc049c-747b-11e8-8dc9-3172c86d482e.png">

**Comment by lmorchard** [comment]
Some implementation notes off the top of my head:

* On the extension side, we'll need to accept a message to set & clear a temporary theme such that it:
  1. does *not* get saved to local storage
  1. gets replaced with the last chosen theme on clear
  1. gets replaced with the next chosen theme, in case we somehow miss clearing it

* On web side in the preview component, send a message to set temporary theme on rollover. On rolloff, clear temporary theme.

Because this is so ephemeral, we can probably skip adding temporary theme support to the Redux store on the web client. We don't need to track it in undo/redo or update web app state. 

If we end up wanting to display some feedback in the web app on rollover, then we probably should add it to Redux store so that React components can use it.

**Comment by Shivansh2407** [comment]
Can I please work on this issue and also please explain me from where should I start?

**Comment by rebmullin** [comment]
hey @ValentinaPC, is it possible to QA this? It should be on stage to be reviewed?
