### ISSUE TITLE
Randomize order of preset themes

### ISSUE THREAD

**Issue by sevaan** [mozilla/FirefoxColor#366]
I feel like randomizing the order of the preset themes will add a little freshness everytime the user goes into Firefox Color.

I'm starting to get a little blindness to them, and I think randomizing the order will help keep things dynamic.

**Comment by lmorchard** [comment]
A couple implementation notes, because this could present a confusing gotcha:

* The first obvious thought is to randomize directly in [the PresetThemeSelector component](https://github.com/mozilla/FirefoxColor/blob/master/src/web/lib/components/PresetThemeSelector/index.js#L13). However, this will result in the list re-randomizing every time the component renders - which will probably be every time anything changes anywhere on the page.

* So, the place to randomize is [in `lib/themes.js` where `presetThemes` is constructed and sorted](https://github.com/mozilla/FirefoxColor/blob/master/src/lib/themes.js#L149). That way, the randomization happens once per page load.

**Comment by a8t** [comment]
This seems like something I could try to do! My first open source contribution, so sorry if there are hiccups.
