### ISSUE TITLE
The "Delete" button from the "Custom Background Image" area does not have any hover effect or tooltip

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#475]
**[Affected versions]:**
- Firefox 62.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (1.2.0) custom built on 10/1/2018 installed.
- Have an image up to 1MB saved to your PC.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Firefox Color" toolbar button.
2. Click the "Custom backgrounds" tab and upload the image from prerequisites.
3. Hover the "Delete" button from the right part of the recently uploaded image.
4. Observe the behavior.

**[Expected result]:**
- The button is highlighted and a tooltip is displayed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- This issue is not reproducible with the other buttons from the same area.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/46285988-1dbcc480-c586-11e8-9840-a32b88eea035.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is partially fixed, the "Delete" button has a highlight effect but it does not have a tooltip and the mouse cursor does not change into a hand pointer. Verified with the latest Firefox Color custom build 2.0.0 (10/09/2018) on Windows 10 x64, Mac 10.13.3 and Arch Linux.

Considering this I will reopen this issue.

Attached a screen recording of the issue:

![rec of the issue - delete button](https://user-images.githubusercontent.com/37875464/46673029-8983da80-cbe1-11e8-9e47-1e80a34fb548.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and now the button has a tooltip, however, it is not the appropriate tooltip for this button, we should use something along the lines of "Remove" or "Delete"

Considering this I will reopen this issue.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Color custom build (11/15/2018) on Windows 10 x64, Mac 10.13.3 and Arch Linux.
