### ISSUE TITLE
Consider adding new theme properties to editor

### ISSUE THREAD

**Issue by lmorchard** [mozilla/FirefoxColor#70]
From [These Weeks in Firefox: Issue 32 ](https://blog.nightly.mozilla.org/2018/02/15/these-weeks-in-firefox-issue-32/):

> The WebExtension theme API now supports specifying colors for frame_inactive, tab_loading, icons and icons_attention, button_background, button_background_hover and button_background_active, toolbar_field_separator.

Need to play with these and see exactly what they do, filing this issue to not forget about it.

**Comment by johngruen** [comment]
Also added 
```
colors.arrowpanel
colors.arrowpanel_text
colors.arrowpanel_border
```

**Comment by nt1m** [comment]
Small note: They're named `popup_` now, not `arrowpanel_`.

**Comment by johngruen** [comment]
How about we do something like this:

1. Somewhere on the page we add an advanced mode
2. Hitting the toggle does the following:
* Displays a panel UI since these accept theme props as well
* Moves all of the theme elements to a grid view and shows an exhaustive list
3. Saving an advanced mode theme will add some kind of additional badge to saved themes

For a list of available theme APIs see the colors section of the [MDN Themes page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme).

I also made a [demo add-on](https://github.com/johngruen/ThemeDemo) that shows all the colors in action. Look at the manifest to see all the keys.

Here are some bad sketches of the this proposal:
1. Current UI with a toggle
![img_6498](https://user-images.githubusercontent.com/3323249/39757917-52ee27dc-529c-11e8-941d-81c728583534.jpg)
2. Proposed advanced mode UI
![img_6499](https://user-images.githubusercontent.com/3323249/39757918-52fd9d02-529c-11e8-8f81-38e1800dcff3.jpg)

**Comment by nt1m** [comment]
I like the idea! However, I think the popup and popup_text properties should be part of the "normal" package. It covers a rather big UI surface, and it's a common use-case to make the panels match the main UI (and it makes sense to do this for the preset themes as well).
