### ISSUE TITLE
.xpi should be hosted on AMO

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#812]
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1561541

The install should originate from the AMO details homepage. This will help prevent the installation warning error from being thrown. :) 

** Details for migrating users who installed the .xpi from the website **

- We need to create one more unlisted version of the .xpi that is hosted on the Color website. The update URL needs to be removed from this version. 

- Then take the version without the update URL and put it somewhere on the server hosting Color. 

- Then make the JSON update file point to it. 

Users with an update URL will update to that version and will be now on the same update channel as everyone else.

/ cc @jvillalobos.

**Comment by Rob--W** [comment]
> We need to create one more unlisted version of the .xpi that is hosted on the Color website. The update URL needs to be removed from this version.

This has been done. Not intentionally (#828), but it's done anyway.

> Then take the version without the update URL and put it somewhere on the server hosting Color.

What's the difference between this and the previous point?

> Then make the JSON update file point to it.

https://testpilot.firefox.com/files/FirefoxColor@mozilla.com/updates.json currently contains:

```
{
    "addons": {
        "FirefoxColor@mozilla.com": {
            "updates": [
                {
                    "update_hash": "sha256:7aa034f253b80c7682a006cf1bbca1d14cb23282a638bf95c0c5e289f9633e9f",
                    "update_link": "https://testpilot.firefox.com/files/FirefoxColor@mozilla.com/latest",
                    "version": "2.1.4"
                }
            ]
        }
    }
}
```

... and the linked xpi does not contain `update_url`, as desired.

Everything is set, except the part where we publish the xpi on AMO.

Using my special review permissions, I am able to see that the last successfuly development XPI was version "2.1.4" on April 30th. The most recent deployment has failed though: https://circleci.com/gh/mozilla/FirefoxColor/1847
```
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/FirefoxColor-github%40mozilla.com/versions/2.1.4/

status: 403
response: {"detail":"Before starting, please read and accept our Firefox Add-on Distribution Agreement as well as our Review Policies and Rules. The Firefox Add-on Distribution Agreement also links to our Privacy Notice which explains how we handle your information."}
```

Since automatic signing is currently broken, and version numbers cannot be used, I recommend that we do not automatically sign the generated XPI.
To test on release, the unsigned add-on can be loaded as a temporary add-on via `about:debugging`.
On DevEd/Nightly, the unsigned add-on can be installed after setting `xpinstall.signatures.required=false` at `about:config`.

What we do need is a way to generate a xpi, so we can (manually) upload it to AMO.
