### ISSUE TITLE
Create a static page so we can download dev and stage's xpi

### ISSUE THREAD

**Issue by rebmullin** [mozilla/FirefoxColor#845]
We should create a static page which links out from the "Get Firefox Color" btn on dev and stage only. This page will have links so that we can download the dev and stage xpis.

The I841 [fix](#842) only addressed the url for prod so this is a follow up for that. See more here:

https://github.com/mozilla/FirefoxColor/pull/842#discussion_r332041803

**Comment by Rob--W** [comment]
Were you planning to work on this @rebmullin ? To test the current master, I wanted to push it to the `development` branch to update gh-pages, but that did not work because in the current build process, there is an attempt to sign the add-on: https://github.com/mozilla/FirefoxColor/blob/cb5a6437739569629b315b895e6c0f2f1d612a3c/package.json#L60

The fix is to not sign the add-on, but to build an unsigned addon (e.g. through a `xpi:dev` command similar to `xpi:stage` / `xpi:production`) and link to that via the button, or the page that is described here. After removing the `sign` step, it will be possible to preview changes by pushing to the development branch.

**Comment by rebmullin** [comment]
hey @Rob--W,

yes I still plan to work on this :) Sorry for the delay and that this is blocking the dev deploy. I posted a PR - #912 - which I am hoping can be an interim fix 🤞 

Regarding this static page. I have a few questions:

1. you suggested linking out to the build urls but I am not sure - what would be the URLS for each env. I guess that's not too clear to me. 
2. where would this page live?

**Comment by Rob--W** [comment]
> 1. you suggested linking out to the build urls but I am not sure - what would be the URLS for each env. I guess that's not too clear to me.

For stage and prod, the URLs are here: https://github.com/mozilla/FirefoxColor#build-test-and-publish-add-on
These names are defined here:
https://github.com/mozilla/FirefoxColor/blob/c55fc2cad3ebe8591433082a2a255141f21c170c/package.json#L45-L46

There is no development name yet, but I was thinking of "firefox-color-dev-unsigned.xpi"

> 2. where would this page live?

Something like `build/web/testing.html` (from `src/web/`?). It would definitely be used as SITE_URL on the development branch, and possibly also on the stage branch. Not on production though.
