### ISSUE TITLE
Exported themes cannot be re-imported

### ISSUE THREAD

**Issue by narFnarF** [mozilla/FirefoxColor#909]
After making a theme with Firefox Color and exporting it to zip or xpi, the exported file cannot be re-imported in Firefox (for example: to bring it to another computer or share with friend)

Steps to reproduce
1. Install the Firefox Color extension
1. Use the Random button to make a new theme
1. Click export
1. Name the theme
1. Click to download both the zip and the xpi files
1. In Firefox, go to the Extension manager
1. Click the Gear button and select Install from a file
1. Select either the zip or xpi file created earlier

Current result:
Firefox display an error message about the imported file being corrupted. The theme is not imported.

Expected result:
Firefox import the theme and activate it, similar to when we install any other theme from the store.

**Comment by Rob--W** [comment]
Does it work if you load it as an unpacked extension from `about:debugging`? If so, then the package is fine, but it's just that Firefox does not allow unsigned add-ons to be installed, for security reasons.

To fix that, you need to submit the theme to https://addons.mozilla.org . see the "Developer Hub" to learn more - https://addons.mozilla.org/en-US/developers/ .

If you want to share the theme without submitting it to AMO (e.g. because you want to share the theme with a friend), use the Share link instead. Then you will get a link to color.firefox.com that your friend can use.

**Comment by narFnarF** [comment]
Ah yes, I see now.

I tried using `about:debugging` and it did work.

So I guess I just misunderstood.
